project:
  type: book
  output-dir: docs

book:
  title: "An Introduction to Statistical Learning (Non Official Solution Book)"
  author: "Angel Feliz"
  reader-mode: true
  page-navigation: true
  navbar:
    pinned: true
  sidebar:
    pinned: true

  page-footer:
    left: |
      Non official solitions of An Introduction to Statistical Learning 
      Second Edition
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/AngelFelizR/ISL-Solutuon-Book
  repo-branch: main
  chapters:
  - index.qmd
  - part: "Teorical Summary"
    chapters: 
      - modeling-process.qmd
      - model-performance.qmd
      - generalized-linear-models.qmd
      - generative-classification-models.qmd
      - flexible-regression.qmd
      - non-parametric-models.qmd
      - resampling-methods.qmd
  - part: "Exercise Solutions"
    chapters:
      - 02-execises.qmd
      - 03-execises.qmd
      - 04-execises.qmd
      - 05-execises.qmd
      
format:
  html:
    theme:
      - cosmo
    code-link: true
    author-meta: "Angel Feliz"
    callout-appearance: simple
    toc-depth: 4

execute:
  warning: false

editor: source
