project:
  type: book
  output-dir: docs

book:
  title: "Machine Learning with R Notes"
  author: "Angel Feliz"
  reader-mode: true
  page-navigation: true
  navbar:
    pinned: true
  sidebar:
    pinned: true

  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/AngelFelizR/ISL-Solutuon-Book
  repo-branch: main
  chapters:
  - index.qmd
  - part: "Summary Notes"
    chapters: 
      - 01-modeling-process.qmd
      - 02-feature-engineering.qmd
      - 03-model-performance.qmd
      - 04-resampling-methods.qmd
      - 05-generalized-linear-models.qmd
      - 06-generative-classification-models.qmd
      - 07-non-parametric-models.qmd
      - 08-survival-analysis.qmd
      - 09-unsupervised-learning.qmd
  - part: "ISLR Execices 2nd Edition"
    chapters:
      - execises-02.qmd
      - execises-03.qmd
      - execises-04.qmd
      - execises-05.qmd
      - execises-11.qmd
      
format:
  html:
    theme:
      - cosmo
    code-link: true
    author-meta: "Angel Feliz"
    callout-appearance: simple
    toc-depth: 4

execute:
  warning: false

editor: source
